config/routes.rb
RailsApp::Application.routes.draw do

  match "blog" => "blog#index", :as => :blog_index
  match "post/:path" => "blog#post", :as => :blog_post
  match "contact" => "contact#index", :as => :contact_index
  match "portfolio" => "portfolio#index", :as => :portfolio_index
  match "portfolio/:path" => "portfolio#project", :as => :portfolio_project

  root :to => 'home#index'
  
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/models/post.rb
class Post
  include MongoMapper::Document
  plugin Joint
  
  key :title,              String, 	:default => ""
  key :text,               String, 	:default => ""
  key :path,          		 String, 	:default => ""
  key :tags,          		 Array,   :default => []
  key :created_at,   			 Time,    :default => lambda {Time.now}
  key :published_at,   		 Time,    :default => nil
  key :published,      	 	 Boolean, :default => false
  key :link_youtube,       String, :default => false
  key :comments,					 Array, :default => []
  attachment :image528x260
  scope :published, where(:published=>true)
    





end

app/models/tag.rb
class Tag
  include MongoMapper::Document

  
  key :name,              String, 	:default => ""




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_controller.rb
# encoding: utf-8
class BlogController < ApplicationController
 
	
  
  def index
    @posts=Post.published.sort(:published_at.desc)
  end

  def post
    @post=Post.find_by_path(params[:path])
  end





 
end

app/controllers/contact_controller.rb
# encoding: utf-8
class ContactController < ApplicationController
 
	# 
  # Tela inicial do site
  # 
  # 
  # def index
  #   Teste.new({:name=>"teste"}).save
  #   render json: {:teste=>Teste.find_one.name}
  # end





 
end

app/controllers/home_controller.rb
# encoding: utf-8
class HomeController < ApplicationController
 
	# 
  # Tela inicial do site
  # 
  # 
  # def index
  #   Teste.new({:name=>"teste"}).save
  #   render json: {:teste=>Teste.find_one.name}
  # end





 
end

app/controllers/portfolio_controller.rb
# encoding: utf-8
class PortfolioController < ApplicationController
 
	# 
  # Tela inicial do site
  # 
  # 
  # def index
  #   Teste.new({:name=>"teste"}).save
  #   render json: {:teste=>Teste.find_one.name}
  # end





 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog/index.html.erb
<!-- masthead -->
<div id="masthead">
	<span class="head">Blog</span><span class="subhead">this is a sub heading</span>
	<ul class="breadcrumbs">
		<li><a href="index.html">home</a></li>
		<li>/ blog</li>
	</ul>
</div>
  	<!-- ENDS masthead -->
  	
  	
  	
<!-- posts list -->
<div id="posts-list">
  	
	<article class="format-standard">
		
		<div class="feature-image">
			<a href="img/slides/01.jpg" data-rel="prettyPhoto"><img src="img/slides/01.jpg" alt="Alt text" /></a>
		</div>
		
		<h1><a href="single.html" class="post-heading">Lorem ipsum dolor amet</a></h1>
		<div class="meta">
			<span class="entry-date">23 Sep, 2011</span>
			in <span class="categories"><a href="#">Category 1</a>, <a href="#">Category 2</a></span>
		</div>
		
		
		<div class="excerpt">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed.
		</div>
		
		<a href="single.html" class="read-more">read more</a>
		
	</article>
	
	
	<article class="format-standard">
		
		<div class="feature-image">
			<a href="img/slides/02.jpg" data-rel="prettyPhoto"><img src="img/slides/02.jpg" alt="Alt text" /></a>
		</div>
		
		<h1><a href="single.html" class="post-heading">Lorem ipsum dolor amet</a></h1>
		<div class="meta">
			<span class="entry-day">23</span>
			<span class="entry-year">sep 2011</span>
		</div>
		
		
		<div class="excerpt">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed.
		</div>
		
		<a href="single.html" class="read-more">read more</a>
		
	</article>
	
	
	<article class="format-standard">
		
		<div class="feature-image">
			<a href="img/slides/03.jpg" data-rel="prettyPhoto"><img src="img/slides/03.jpg" alt="Alt text" /></a>
		</div>
		
		<h1><a href="single.html" class="post-heading">Lorem ipsum dolor amet</a></h1>
		<div class="meta">
			<span class="entry-day">23</span>
			<span class="entry-year">sep 2011</span>
		</div>
		
		
		<div class="excerpt">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed.
		</div>
		
		<a href="single.html" class="read-more">read more</a>
		
	</article>
  		
  		
  	</div>
  	<!-- ENDS posts list -->
  	
  	
  	<!-- sidebar -->
  	<aside id="sidebar">
  		
  		<div class="block">
    		<h4>categories</h4>
		<ul>
			<li class="cat-item"><a href="#" title="View all posts">Film and video</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Print</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Photo and lomo</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Habitant morbi</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Film and video</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Print</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Photo and lomo</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Habitant morbi</a></li>
		</ul>
  		</div>
  		
  		<div class="block">
    		<h4>archives</h4>
		<ul>
			<li class="cat-item"><a href="#" title="View all posts">January</a></li>
			<li class="cat-item"><a href="#" title="View all posts">February</a></li>
			<li class="cat-item"><a href="#" title="View all posts">March</a></li>
		</ul>
  		</div>
  	
  	</aside>
  	<div class="clearfix"></div>
<!-- ENDS sidebar -->


<!-- pager -->
		<ul class="pager">
	<li class="paged">Page 1 of 2</li>
	<li class="active"><a href="#">1</a></li>
	<li><a href="#">2</a></li>
	<li><a href="#">3</a></li>
</ul>
<div class="clearfix"></div>
  	<!-- ENDS pager -->

app/views/blog/post.html.erb
<!-- masthead -->
<div id="masthead">
	<span class="head">Blog</span><span class="subhead">this is a sub heading</span>
	<ul class="breadcrumbs">
		<li><a href="index.html">home</a></li>
		<li>/ blog</li>
	</ul>
</div>
<!-- ENDS masthead -->
  	
  	
  	
<!-- posts content -->
<div id="post-content">

		
	<div class="feature-image">
		<a href="img/slides/01.jpg" data-rel="prettyPhoto"><img src="img/slides/01.jpg" alt="Alt text" /></a>
	</div>
	
	<h1 class="post-heading">Lorem ipsum dolor amet</h1>
	<div class="meta">
		<span class="entry-date">23 Sep, 2011</span>
		in <span class="categories"><a href="#">Category 1</a>, <a href="#">Category 2</a></span>
	</div>
	
	<div class="content-area">
		Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed.Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed.Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed.
	</div>
		
  		
  		<!-- comments list -->
	<div id="comments-wrap">
		<h3 class="heading">5 COMMENTS</h3>
		<ol class="commentlist">
		           
			<li class="comment even thread-even depth-1" id="li-comment-1">
				
				<div id="comment-1" class="comment-body clearfix">
			     	<img alt='' src='http://0.gravatar.com/avatar/4f64c9f81bb0d4ee969aaf7b4a5a6f40?s=35&amp;d=&amp;r=G' class='avatar avatar-35 photo' height='35' width='35' />      
			     	<div class="comment-author vcard">Jhon</div>
			        <div class="comment-meta commentmetadata">
				  		<span class="comment-date">3 days ago  </span>
						<span class="comment-reply-link-wrap"><a class='comment-reply-link' href='replytocom=23#respond' onclick='return addComment.moveForm("comment-1", "1", "respond", "432")'>Reply</a></span>
						
					</div>
			  		<div class="comment-inner">
				   		<p>Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.</p>
			 		</div>
		     	</div>
		
				<!-- child -->
				<ul class='children'>
		  			<li class="comment even alt depth-2" id="li-comment-2-1">
						<div id="comment-2" class="comment-body clearfix">
							<img alt='' src='http://0.gravatar.com/avatar/4f64c9f81bb0d4ee969aaf7b4a5a6f40?s=35&amp;d=&amp;r=G' class='avatar avatar-35 photo' height='35' width='35' />      
		      				<div class="comment-author vcard">Jhon</div>
							<div class="comment-meta commentmetadata">
		  						<span class="comment-date">1 hour ago  </span>
								<span class="comment-reply-link-wrap"><a class='comment-reply-link' href='replytocom=24#respond' onclick='return addComment.moveForm("comment-2", "2", "respond", "432")'>Reply</a></span>
							</div>
		  					<div class="comment-inner">
					   			<p>Pellentesque ornare sem lacinia quam venenatis vestibulum. Vestibulum id ligula porta felis euismod semper. Sed posuere consectetur est at lobortis.</p>
		     			 	</div>
		 				</div>
					</li>
					
					<li class="comment odd alt depth-2" id="li-comment-2-2">
						<div id="comment-3" class="comment-body clearfix">
							<img alt='' src='http://0.gravatar.com/avatar/4f64c9f81bb0d4ee969aaf7b4a5a6f40?s=35&amp;d=&amp;r=G' class='avatar avatar-35 photo' height='35' width='35' />      
		      				<div class="comment-author vcard">Jhon</div>
							<div class="comment-meta commentmetadata">
		  						<span class="comment-date">1 hour ago  </span>
								<span class="comment-reply-link-wrap"><a class='comment-reply-link' href='replytocom=24#respond' onclick='return addComment.moveForm("comment-3", "2", "respond", "432")'>Reply</a></span>
							</div>
		  					<div class="comment-inner">
					   			<p>Pellentesque ornare sem lacinia quam venenatis vestibulum. Vestibulum id ligula porta felis euismod semper. Sed posuere consectetur est at lobortis.</p>
		     			 	</div>
		 				</div>
					</li>
					
					
				</ul>
				<!-- ENDS child -->
			</li>
			
			
			<li class="comment odd thread-even depth-1" id="li-comment-3">
				
				<div id="comment-4" class="comment-body clearfix">
			     	<img alt='' src='http://0.gravatar.com/avatar/4f64c9f81bb0d4ee969aaf7b4a5a6f40?s=35&amp;d=&amp;r=G' class='avatar avatar-35 photo' height='35' width='35' />      
			     	<div class="comment-author vcard">Jhon</div>
			        <div class="comment-meta commentmetadata">
				  		<span class="comment-date">3 days ago  </span>
						<span class="comment-reply-link-wrap"><a class='comment-reply-link' href='replytocom=23#respond' onclick='return addComment.moveForm("comment-4", "1", "respond", "432")'>Reply</a></span>
						
					</div>
			  		<div class="comment-inner">
				   		<p>Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.</p>
			 		</div>
		     	</div>
		    </li>
		    
		    <li class="comment even thread-even depth-1" id="li-comment-4">
				
				<div id="comment-5" class="comment-body clearfix">
			     	<img alt='' src='http://0.gravatar.com/avatar/4f64c9f81bb0d4ee969aaf7b4a5a6f40?s=35&amp;d=&amp;r=G' class='avatar avatar-35 photo' height='35' width='35' />      
			     	<div class="comment-author vcard">Jhon</div>
			        <div class="comment-meta commentmetadata">
				  		<span class="comment-date">3 days ago  </span>
						<span class="comment-reply-link-wrap"><a class='comment-reply-link' href='replytocom=23#respond' onclick='return addComment.moveForm("comment-5", "1", "respond", "432")'>Reply</a></span>
						
					</div>
			  		<div class="comment-inner">
				   		<p>Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.</p>
			 		</div>
		     	</div>
		    </li>
		   
			
		</ol>
	</div>
	<!-- ENDS comments list -->
	
	
	<!-- Respond -->				
	<div id="respond">
		
		<div class="cancel-comment-reply"><a rel="nofollow" id="cancel-comment-reply-link" href="#respond" style="display:none;">Cancel reply</a></div>
		<form action="single.html" method="post" id="commentform">
			<h3 class="heading">LEAVE A REPLY</h3>
			<input type="text" name="author" id="author" value="" tabindex="1" />
			<label for="author">Name <small>*</small></label><br/>
		
			<input type="text" name="email" id="email" value="" tabindex="2" />
			<label for="email">Email <small>*</small> <span>(not published)</span></label><br/>
		
			<input type="text" name="url" id="url" value="" tabindex="3" />
			<label for="url">Website</label>
		
			<textarea name="comment" id="comment"  tabindex="4"></textarea>
				
			<p><input name="submit" type="submit" id="submit" tabindex="5" value="Post" /></p>
			
			<input type='hidden' name='comment_post_ID' value='' id='comment_post_ID' />
			<input type='hidden' name='comment_parent' id='comment_parent' value='0' />	
		</form>
	</div>
	<div class="clearfix"></div>
	<!-- ENDS Respond -->
		
		
  		
</div>
<!-- ENDS posts content -->


<!-- sidebar -->
<aside id="sidebar">
	
	<div class="block">
		<h4>categories</h4>
<ul>
	<li class="cat-item"><a href="#" title="View all posts">Film and video</a></li>
	<li class="cat-item"><a href="#" title="View all posts">Print</a></li>
	<li class="cat-item"><a href="#" title="View all posts">Photo and lomo</a></li>
	<li class="cat-item"><a href="#" title="View all posts">Habitant morbi</a></li>
	<li class="cat-item"><a href="#" title="View all posts">Film and video</a></li>
	<li class="cat-item"><a href="#" title="View all posts">Print</a></li>
	<li class="cat-item"><a href="#" title="View all posts">Photo and lomo</a></li>
	<li class="cat-item"><a href="#" title="View all posts">Habitant morbi</a></li>
</ul>
	</div>
	
	<div class="block">
		<h4>archives</h4>
<ul>
	<li class="cat-item"><a href="#" title="View all posts">January</a></li>
	<li class="cat-item"><a href="#" title="View all posts">February</a></li>
	<li class="cat-item"><a href="#" title="View all posts">March</a></li>
</ul>
	</div>

</aside>
<div class="clearfix"></div>
<	!-- ENDS sidebar -->

app/views/contact/index.html.erb
			
<!-- masthead -->
<div id="masthead">
	<span class="head">Contact</span><span class="subhead">this is a sub heading</span>
	<ul class="breadcrumbs">
		<li><a href="index.html">home</a></li>
		<li>/ contact</li>
	</ul>
</div>
<!-- ENDS masthead -->
  	
	        	
	        	
<!-- page content -->
<div id="page-content">
		        	
							
	<!-- Map -->
	<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=true" /></script>
	<script type="text/javascript">
		function initialize() {
			var latlng = new google.maps.LatLng(-34.397, 150.644);
			var myOptions = {
			  zoom: 8,
			  center: latlng,
			  mapTypeId: google.maps.MapTypeId.ROADMAP
		};
		var map = new google.maps.Map(document.getElementById("map"),
		    myOptions);
		}
	</script>

	<div id="map-holder">
		<div id="map"></div>
	</div>

	<!-- ENDS Map -->
		
			
	<p>
		Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi.
	</p>

	<!-- form -->
	<script type="text/javascript" src="js/form-validation.js"></script>
	<form id="contactForm" action="#" method="post">
		<h3 class="heading">Contact us using this form</h3>
		<p> Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget.</p>
		<fieldset>
			<div>
				<input name="name"  id="name" type="text" class="form-poshytip" title="Enter your full name" />
				<label>Name</label>
			</div>
			<div>
				<input name="email"  id="email" type="text" class="form-poshytip" title="Enter your email address" />
				<label>Email</label>
			</div>
			<div>
				
				<input name="web"  id="web" type="text" class="form-poshytip" title="Enter your website" />
				<label>Website</label>
			</div>
			<div>
				<textarea  name="comments"  id="comments" rows="5" cols="20" class="form-poshytip" title="Enter your comments"></textarea>
			</div>
			
			<!-- send mail configuration -->
			<input type="hidden" value="email@yourserver.com" name="to" id="to" />
			<input type="hidden" value="Enter the subject here" name="subject" id="subject" />
			<input type="hidden" value="send-mail.php" name="sendMailUrl" id="sendMailUrl" />
			<!-- ENDS send mail configuration -->
			
			<p><input type="button" value="Send" name="submit" id="submit" /> <span id="error" class="warning">Message</span></p>
		</fieldset>
		
	</form>
	<p id="sent-form-msg" class="success">Form data sent. Thanks for your comments.</p>
	<!-- ENDS form -->
		
	
</div>
<!-- ENDS page content -->
	
	
<!-- sidebar -->
<aside id="sidebar">
	<div class="block">
		<h4>Address</h4>
		<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor si tincidunt quis, accumsan porttitor, facilisis luctus, mets.</p>
		
		<ul class="address-block">
			<li class="address">Address line, city, state ZIP</li>
			<li class="phone">+123 456 789</li>
			<li class="mobile">+123 456 789</li>
			<li class="email"><a href="mailto:email@server.com">email@server.com</a></li>
		</ul>
		
	</div>	        	
</aside>
<div class="clearfix"></div>
<!-- ENDS sidebar -->
<!-- Start google map -->
<script>initialize();</script>

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js">

	<head>
		<meta charset="utf-8"/>
		<title>Open Your Mind</title>
		<!--[if lt IE 9]>
			<script src="js/css3-mediaqueries.js"></script>
		<![endif]-->
		<link rel="stylesheet" media="all" href="css/style.css"/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<!-- Adding "maximum-scale=1" fixes the Mobile Safari auto-zoom bug: http://filamentgroup.com/examples/iosScaleBug/ -->
		
		
		<!-- JS -->
		<script src="js/jquery-1.6.4.min.js"></script>
		
		<!--  <script src="js/less-grid-4.js"></script> -->
		<script src="js/custom.js"></script>
		<script src="js/tabs.js"></script>
		<script src="js/moveform.js"></script>
		
		<!-- Masonry -->
		<script src="js/masonry.min.js" ></script>
		<script src="js/imagesloaded.js" ></script>
		<!-- ENDS Masonry -->
		
		<!-- Tweet -->
		<link rel="stylesheet" href="css/jquery.tweet.css" media="all"  /> 
		<script src="js/tweet/jquery.tweet.js" ></script> 
		<!-- ENDS Tweet -->
		
		<!-- superfish -->
		<link rel="stylesheet" media="screen" href="css/superfish.css" /> 
		<script  src="js/superfish-1.4.8/js/hoverIntent.js"></script>
		<script  src="js/superfish-1.4.8/js/superfish.js"></script>
		<script  src="js/superfish-1.4.8/js/supersubs.js"></script>
		<!-- ENDS superfish -->
		
		<!-- prettyPhoto -->
		<script  src="js/prettyPhoto/js/jquery.prettyPhoto.js"></script>
		<link rel="stylesheet" href="js/prettyPhoto/css/prettyPhoto.css"  media="screen" />
		<!-- ENDS prettyPhoto -->
		
		<!-- poshytip -->
		<link rel="stylesheet" href="js/poshytip-1.1/src/tip-twitter/tip-twitter.css"  />
		<link rel="stylesheet" href="js/poshytip-1.1/src/tip-yellowsimple/tip-yellowsimple.css"  />
		<script  src="js/poshytip-1.1/src/jquery.poshytip.min.js"></script>
		<!-- ENDS poshytip -->
		
		
		<!-- GOOGLE FONTS -->
		<link href='http://fonts.googleapis.com/css?family=Allan:700' rel='stylesheet' type='text/css'>
		
		<!-- Flex Slider -->
		<link rel="stylesheet" href="css/flexslider.css" >
		<script src="js/jquery.flexslider-min.js"></script>
		<!-- ENDS Flex Slider -->
		
		
		<!--[if IE 6]>
		<link rel="stylesheet" href="css/ie6-hacks.css" media="screen" />
		<script type="text/javascript" src="js/DD_belatedPNG.js"></script>
			<script>
          		/* EXAMPLE */
          		DD_belatedPNG.fix('*');
        	</script>
		<![endif]-->
		
		<!-- Lessgrid -->
		<link rel="stylesheet" media="all" href="css/lessgrid.css"/>
		
		<!-- modernizr -->
		<script src="js/modernizr.js"></script>
		
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>

	</head>
<body>
<%=render "shared/header"%>
<div id="main">
	<!-- social -->
	<div id="social-bar">
		<ul>
			<li><a href="http://www.facebook.com"  title="Become a fan"><img src="img/social/facebook_32.png"  alt="Facebook" /></a></li>
			<li><a href="http://www.twitter.com" title="Follow my tweets"><img src="img/social/twitter_32.png"  alt="Facebook" /></a></li>
			<li><a href="http://www.google.com"  title="Add to the circle"><img src="img/social/google_plus_32.png" alt="Facebook" /></a></li>
		</ul>
	</div>
	<!-- ENDS social -->
	
	<!-- Content -->
	<div id="content">
	<%= yield %>
	</div>
	<!-- ENDS content -->

	<div class="clearfix"></div>
	<div class="shadow-main"></div>
</div>
<%=render "shared/footer"%>
</body>
</html>

app/views/shared/_header.html.erb
<!-- mobile-nav -->
<div id="mobile-nav-holder">
	<div class="wrapper">
		<ul id="mobile-nav">
			<li><a href="<%=root_path%>">home</a></li>
			<li><a href="<%=blog_index_path%>">blog</a></li>
			<li><a href="<%=portfolio_index_path%>">portfolio</a></li>
			<li><a href="<%=contact_index_path%>">contact</a></li>
		</ul>
		<div id="nav-open"><a href="#">Menu</a></div>
	</div>
</div>
<!-- ENDS mobile-nav -->
	
<header>
	
		
	<div class="wrapper">
			
		<a href="index.html" id="logo"><img  src="img/logo.png" alt="Tandem"></a>
		
		<nav>
			<ul id="nav" class="sf-menu">
				<li><a href="<%=root_path%>">home<span class="subheader">welcome</span></a></li>
				<li><a href="<%=blog_index_path%>">blog<span class="subheader">read me</span></a></li>
				<li><a href="<%=portfolio_index_path%>">portfolio<span class="subheader">recent work</span></a></li>
				<li><a href="<%=contact_index_path%>">contact<span class="subheader">get in touch</span></a></li>
			</ul>
		</nav>
		
		<div class="clearfix"></div>
		
	</div>
</header>